<?php

namespace Ugosansh\Bundle\Image\EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function findBySize($id, $width, $height)
    {
        try {
            $collection = $this->createQueryBuilder('i')
                ->select('i')
                ->where('(i.id = :id OR i.parent = :id)')
                ->andWhere('i.width = :width')
                ->andWhere('i.height = :height')
                ->setParameters(['id' => $id, 'width' => $width, 'height' => $height])
                ->getQuery()
                ->getResult();

            if ($collection) {
                return end($collection);
            }
        } catch(NoResultException $e) {
            return null;
        }
    }

}
