Ugosansh\Bundle\Image\EntityBundle\Entity\Image:
    properties:
        id:
           read_only: true
        parent:
          exclude: true
          expose: false
        childs:
          exclude: true
          expose: false
        binarySource:
          exclude: true
          expose: false
    relations:
      - rel: self
        href:
          route: image_info
          parameters:
            id: expr(object.getId())
          absolute: true
      - rel: url
        href:
          route: image_get
          parameters:
            slug: expr(object.getSlug())
            _format: expr(object.getExtension())
          absolute: true
      - rel: childs
        href:
          route: image_childs
          parameters:
            id: expr(object.getId())
          absolute: true
      - rel: parent
        exclusion:
          exclude_if: expr(null === object.getParent())
        href:
          route: image_info
          parameters:
            id: expr(object.getParent().getId())
          absolute: true

